### PR TITLE
Add git commands 'cherry-pick', 'reset' and 'branch/tag -d'

### PR DESCRIPTION
**Pull request by AlterDepp**
I added a few commands I often use. I tested it with version v1.1, which is available on vim.org and rebased it on master.

### CODE REVIEW

**Comment by aschrab** [comment]
These seem like useful features to me. I'm not entirely happy with the mappings for reset, but I don't have a better idea for them either. I did add a couple of comments on the commit about bits of the docs that look slightly outdated.

:+1:

**Comment by AlterDepp** [comment]
I added a commit to fix the typos.

**Comment by AlterDepp** [comment]
Hi @aschrab, will you pull it and create a new version of the plugin at vim.org?
Stefan

**Comment by aschrab** [comment]
I don't have access to pull changes into this repository. I'm just a user/contributor like you are.

**Comment by gregsexton** [comment]
Thanks for adding these features. I'm happy with the mappings that begin with `c` or `d` as these are shadowing edits that you wouldn't be able to perform in a read-only buffer. `b` is useful though and I would like this to remain the motion for moving backwards. Maybe git manipulations should all have the same key prefix? At the cost of a few more keystrokes, this will allow this to expand to as many operations as desired. I'm happy to hear your thoughts and take suggestions on this one.

**Comment by gregsexton** [comment]
Also, apologies this took me so long to get to. :)

**Comment by AlterDepp** [comment]
Which mappings would you suggest?

**Pull request merged**
